apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pushpaka.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushpaka.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.api.env.PORT }}"
  PUSHPAKA_COMPONENT: "{{ .Values.api.env.PUSHPAKA_COMPONENT }}"
  LOG_LEVEL: "{{ .Values.api.env.LOG_LEVEL }}"
  DATABASE_URL: "{{ .Values.api.env.DATABASE_URL }}"
  REDIS_URL: "{{ .Values.api.env.REDIS_URL }}"
  JWT_EXPIRY: "{{ .Values.api.env.JWT_EXPIRY }}"
  CORS_ALLOWED_ORIGINS: "{{ tpl .Values.api.env.CORS_ALLOWED_ORIGINS . }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pushpaka.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushpaka.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.api.env.JWT_SECRET | b64enc }}
