{{- if or .Values.api.ingress.enabled .Values.dashboard.ingress.enabled -}}
{{- if .Values.api.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pushpaka.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushpaka.labels" . | nindent 4 }}
    component: api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.api.ingress.className }}
  ingressClassName: {{ .Values.api.ingress.className }}
  {{- end }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- range .Values.api.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.api.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "pushpaka.fullname" $ }}-api
                port:
                  number: {{ $.Values.api.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- if and .Values.api.ingress.enabled .Values.dashboard.ingress.enabled }}
---
{{- end }}
{{- if .Values.dashboard.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pushpaka.fullname" . }}-dashboard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushpaka.labels" . | nindent 4 }}
    component: dashboard
  {{- with .Values.dashboard.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.dashboard.ingress.className }}
  ingressClassName: {{ .Values.dashboard.ingress.className }}
  {{- end }}
  {{- if .Values.dashboard.ingress.tls }}
  tls:
    {{- range .Values.dashboard.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.dashboard.ingress.hosts }}
    - host: {{ tpl .host $ | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "pushpaka.fullname" $ }}-dashboard
                port:
                  number: {{ $.Values.dashboard.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
