{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pushpaka.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushpaka.labels" . | nindent 4 }}
{{- end }}
