apiVersion: v1
entries:
  pushpaka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-18T01:45:24.462752215Z"
    dependencies:
    - alias: traefik-ingress
      condition: traefik.enabled
      name: traefik
      repository: https://traefik.github.io/charts
      version: 27.0.0
    description: Pushpaka - Self-hosted Cloud Deployment Platform
    digest: 73c74245438ca5bcdb8a19ec954f3cff47d8d008f4a81e51a79e8b8992a0dc61
    home: https://github.com/vikukumar/Pushpaka
    icon: https://raw.githubusercontent.com/vikukumar/Pushpaka/main/branding/logo.svg
    keywords:
    - deployment
    - cloud
    - git
    - docker
    - traefik
    maintainers:
    - email: vikukumar@example.com
      name: Viku Kumar
    name: pushpaka
    sources:
    - https://github.com/vikukumar/Pushpaka
    type: application
    urls:
    - https://pushpaka.vikshro.in/helm/pushpaka-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-18T01:45:24.456809584Z"
