apiVersion: v1
entries:
  pushpaka:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-03-19T16:54:25.757139007Z"
    dependencies:
    - alias: traefik-ingress
      condition: traefik.enabled
      name: traefik
      repository: https://traefik.github.io/charts
      version: 27.0.0
    description: Pushpaka - Self-hosted Cloud Deployment Platform
    digest: 55241f918316207a2d8954bee52da07f3e74606b35021bb467664ebcee0b2793
    home: https://pushpaka.vikshro.in/
    icon: https://raw.githubusercontent.com/vikukumar/Pushpaka/main/branding/logo.svg
    keywords:
    - deployment
    - cloud
    - git
    - docker
    - traefik
    maintainers:
    - email: vikashkumar0037@gmail.com
      name: Vikash Kumar
    name: pushpaka
    sources:
    - https://github.com/vikukumar/Pushpaka
    type: application
    urls:
    - https://pushpaka.vikshro.in/helm/pushpaka-1.0.0.tgz
    version: 1.0.0
generated: "2026-03-19T16:54:25.751157834Z"
